template: true
valuesFilePath: ./values.yml
resources:
  - name: myPropertyBag1
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag2
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag3
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag4
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag5
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag6
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag7
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag8
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag9
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag10
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
pipelines:
  - name: testcron2
    steps:
      - name: basicly
        type: Bash
        execution:
          onExecute:
            - echo hi
      - name: basic2
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag1
            - name: myPropertyBag2
            - name: myPropertyBag3
            - name: myPropertyBag4
            - name: myPropertyBag5
            - name: myPropertyBag6
            - name: myPropertyBag7
            - name: myPropertyBag8
            - name: myPropertyBag9
            - name: myPropertyBag10
          inputSteps:
            - name: basicly
        execution:
          onExecute:
            - echo hi
