template: true
valuesFilePath: ./values.yml

resources:
  - name: myPropertyBag1Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag2Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag3Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag4Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag5Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag6Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag7Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag8Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag9Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: frontendGitPipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag12Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: redisBuildInfoPipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: wwwGitPipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: vaultInitBuildInfoPipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag16Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag17Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: frontendBuildInfoPipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: cpGitPipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: msgPipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag20Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag21Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag22Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag23Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag24Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag28Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag29Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag30Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag31Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag32Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag33Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag34Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag35Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag36Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag37Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag38Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag39Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag40Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag41Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag42Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag43Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag44Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag45Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag46Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag47Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag48Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag49Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag50Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag51Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag52Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: myPropertyBag53Pipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: microGitPipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
  - name: templateFSPipe17
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
pipelines:
  - name: Pipe17
    steps:
      - name: trigger_controlplane_builds
        type: Bash
        execution:
          onExecute:
            - echo hi
      - name: automation_e2e_build
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag1Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: frontend
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag2Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: frontend_publish
        type: Bash
        configuration:
          inputResources:
            - name: frontendGitPipe17
            - name: frontendBuildInfoPipe17
          inputSteps:
            - name: frontend
        execution:
          onExecute:
            - echo hi
      - name: frontend_sonar_scan
        type: Bash
        configuration:
          inputResources:
            - name: frontendGitPipe17
          inputSteps:
            - name: frontend
        execution:
          onExecute:
            - echo hi
      - name: msgPipe17
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag3Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: msg_publish
        type: Bash
        configuration:
          outputResources:
            - name: msgPipe17
          inputSteps:
            - name: msgPipe17
        execution:
          onExecute:
            - echo hi
      - name: msg_clam_scan
        type: Bash
        configuration:
          inputResources:
            - name: cpGitPipe17
          inputSteps:
            - name: msg_publish
        execution:
          onExecute:
            - echo hi
      - name: redis
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag12Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: redis_publish
        type: Bash
        configuration:
          outputResources:
            - name: redisBuildInfoPipe17
          inputSteps:
            - name: redis
        execution:
          onExecute:
            - echo hi
      - name: vault
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag4Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: vault_publish
        type: Bash
        configuration:
          outputResources:
            - name: wwwGitPipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: vault_clam_scan
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag20Pipe17
          inputSteps:
            - name: vault_publish
        execution:
          onExecute:
            - echo hi
      - name: template_build
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag5Pipe17
          outputResources:
            - name: templateFSPipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: micro_build
        type: Bash
        configuration:
          inputResources:
            - name: templateFSPipe17
            - name: myPropertyBag22Pipe17
            - name: myPropertyBag23Pipe17
            - name: microGitPipe17
          inputSteps:
            - name: template_build
        execution:
          onExecute:
            - echo hi
      - name: micro_test
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag24Pipe17
          inputSteps:
            - name: micro_build
        execution:
          onExecute:
            - echo hi
      - name: micro_sonar_scan
        type: Bash
        configuration:
          inputResources:
            - name: microGitPipe17
          inputSteps:
            - name: micro_test
        execution:
          onExecute:
            - echo hi
      - name: template_sonar_scan
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag21Pipe17
          inputSteps:
            - name: template_build
        execution:
          onExecute:
            - echo hi
      - name: vault_init
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag6Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: vault_init_publish
        type: Bash
        configuration:
          outputResources:
            - name: vaultInitBuildInfoPipe17
          inputSteps:
            - name: vault_init
        execution:
          onExecute:
            - echo hi
      - name: inst_build
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag28Pipe17
            - name: myPropertyBag29Pipe17
            - name: myPropertyBag30Pipe17
            - name: myPropertyBag31Pipe17
            - name: myPropertyBag32Pipe17
            - name: myPropertyBag33Pipe17
            - name: myPropertyBag34Pipe17
            - name: myPropertyBag35Pipe17
            - name: myPropertyBag36Pipe17
            - name: myPropertyBag37Pipe17
          inputSteps:
            - name: vault_init_publish
        execution:
          onExecute:
            - echo hi
      - name: inst_clam_scan
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag38Pipe17
          inputSteps:
            - name: inst_build
        execution:
          onExecute:
            - echo hi
      - name: create_snapshot_branch
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag39Pipe17
            - name: myPropertyBag40Pipe17
          inputSteps:
            - name: inst_clam_scan
        execution:
          onExecute:
            - echo hi
      - name: postgres
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag7Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: postgres_publish
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag16Pipe17
          inputSteps:
            - name: postgres
        execution:
          onExecute:
            - echo hi
      - name: postgres_clam_scan
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag43Pipe17
          inputSteps:
            - name: postgres_publish
        execution:
          onExecute:
            - echo hi
      - name: www_clam_scan
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag16Pipe17
          inputSteps:
            - name: www_publish
        execution:
          onExecute:
            - echo hi
      - name: pipelines_router
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag8Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: pipelines_router_publish
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag17Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: build_helm_chart
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag9Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: www
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag41Pipe17
            - name: myPropertyBag42Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: www_publish
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag41Pipe17
            - name: myPropertyBag42Pipe17
          inputSteps:
            - name: www
        execution:
          onExecute:
            - echo hi
      - name: api_build
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag44Pipe17
            - name: myPropertyBag45Pipe17
            - name: myPropertyBag46Pipe17
            - name: myPropertyBag47Pipe17
            - name: myPropertyBag48Pipe17
            - name: myPropertyBag49Pipe17
            - name: myPropertyBag50Pipe17
            - name: myPropertyBag51Pipe17
            - name: myPropertyBag52Pipe17
          inputSteps:
            - name: trigger_controlplane_builds
        execution:
          onExecute:
            - echo hi
      - name: api_clam_scan
        type: Bash
        configuration:
          inputResources:
            - name: myPropertyBag53Pipe17
          inputSteps:
            - name: api_build
        execution:
          onExecute:
            - echo hi
      - name: trigger_post_release
        type: Bash
        configuration:
          inputResources:
            - name: cpGitPipe17
            - name: msgPipe17
            - name: redisBuildInfoPipe17
            - name: vaultInitBuildInfoPipe17
            - name: wwwGitPipe17
          inputSteps:
            - name: msg_clam_scan
            - name: vault_clam_scan
            - name: micro_sonar_scan
            - name: www_clam_scan
            - name: api_clam_scan
        execution:
          onExecute:
            - echo hi