template: true
valuesFilePath: ./values.yml


pipelines:
  - name: testcron
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo hi
      {{ range $i, $e := until 1000 }}
      - name: basic{{$i}}
        type: Matrix
        stepMode: Bash
        configuration:
          multiNode: true
        stepletMultipliers:
          environmentVariables:
            - foo: "foo"
            - foo: "bar"
            - foo: "baz"
          runtimes:
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.16.0
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 12.14.0
        execution:
          onExecute:
            - echo $foo
      {{ end }}
