template: true
valuesFilePath: ./values.yml


pipelines:
  - name: testcron
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo hi
      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo hi
