template: true
valuesFilePath: ./values.yml

resources:
  {{ range $i, $e := until 5 }}
  - name: monitor_cron_trigger{{$i}}
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *' # Every 5 minutes
  {{ end }}

pipelines:
  - name: testcron
    steps:
      {{ range $i, $e := until 2 }}
      - name: basic{{$i}}
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: monitor_cron_trigger{{$i}}
        execution:
          onExecute:
            - echo hi
      {{ end }}
