template: true
valuesFilePath: ./values.yml


pipelines:
  - name: testcron
    steps:
      - name: basicly
        type: Bash
        execution:
          onExecute:
            - echo hi
      - name: basic{{$i}}
        type: Bash
        configuration:
          inputSteps:
            - name: basicly
        execution:
          onExecute:
            - echo hi
