template: true
valuesFilePath: ./values.yml

pipelines:
  - name: testcron
    steps:
      - name: basic
        type: Bash
        execution:
          onExecute:
            - echo hi
      - name: basic1
        type: Bash
        configuration:
          inputSteps:
            - name: basic
        execution:
          onExecute:
            - echo hi
