template: true
valuesFilePath: ./values.yml

resources:
  {{ range $i, $e := until 5 }}
  - name: monitor_cron_trigger{{$i}}
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *' # Every 5 minutes
  {{ end }}

pipelines:
  - name: testcron
    steps:
      - name: basic1
        type: Bash
        configuration:
          inputSteps:
            - name: ag_step_1
        execution:
          onExecute:
            - echo hi

      - name: basic2
        type: Bash
        configuration:
          inputSteps:
            - name: basic1
          runtime:
            type: host
          inputResources:
            - name: monitor_cron_trigger{{$i}}
        execution:
          onExecute:
            - echo hi
