template: true
valuesFilePath: ./values.yml

resources:
  {{ range $i+1, $e := until 5 }}
  - name: monitor_cron_trigger{{$i}}
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *' # Every 5 minutes
  {{ end }}

pipelines:
  - name: testcron
    steps:
      {{ range $i, $e := until 1 }}
      - name: basic{{$i+1}}
        type: Bash
        configuration:
          runtime:
            type: host
          inputResources:
            - name: monitor_cron_trigger{{$i+1}}
        execution:
          onExecute:
            - echo hi
      {{ end }}
      - name: basic1
        type: Bash
        configuration:
          inputSteps:
            - name: basic0
        execution:
          onExecute:
            - echo hi
